spring:
  application:
    name: discovery-server
  config:
    import:
      - configserver:http://localhost:8888
      - configserver:http://localhost:8889
  cloud:
    config:
      label: main
      fail-fast: true